version: '2'

services:
  moodle:
    container_name: h5p-moodle-3.2
    image: tajakobsen/h5p-moodle:3.2.1
    links:
     - "database"
    ports:
     - "80:80"
    environment:
      MOODLE_URL: 'http://localhost'
      MYSQL_HOST: 'database'
      MYSQL_DATABASE: "moodle"
      MYSQL_USER: "moodle"
      MYSQL_PASSWORD: "moodle"
    volumes:
      - "./php.ini:/etc/php/7.0/apache2/conf.d/30-moodle_php.ini"
      - "../../h5p-moodle-plugin:/var/www/html/mod/hvp"
      - "./moodle-config.php:/var/www/html/config.php"
      - "./theme/h5pmods-moodle:/var/www/html/theme/superclean"
  database:
    container_name: h5p-moodle-mysql-3.2
    image: mysql:latest
    environment:
      MYSQL_DATABASE: "moodle"
      MYSQL_ROOT_PASSWORD: "moodle"
      MYSQL_USER: "moodle"
      MYSQL_PASSWORD: "moodle"
    expose:
     - "3306"
    ports:
     - "3306:3306"
    volumes:
     - "./data/mysql:/var/lib/mysql"
