version: '3.1'

services:

  moodle:
    container_name: tmi_learn_lms
    image: bitnami/moodle:3
    ports:
      - 22000:8080
      - 443:8443
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=tmi_learn
      - MOODLE_DATABASE_NAME=tmi_learn
      - MOODLE_DATABASE_PASSWORD=tmi_learn
    volumes:
      - ./local/moodle:/bitnami/moodle
    depends_on:
      - mariadb
    restart: always

  mariadb:
    container_name: tmi_learn_db
    image: mariadb:10.1
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=tmi_learn
      - MYSQL_PASSWORD=tmi_learn
      - MYSQL_DATABASE=tmi_learn
    ports:
      - 22010:3306
    volumes:
      - ./local/data:/var/lib/mysql
    restart: always

  adminer:
    container_name: tmi_web_admin
    image: adminer
    environment:
      - ADMINER_DEFAULT_SERVER=mariadb
    ports:
      - 22020:8080
    restart: always